Handle undef value in lvm::logical_volume
* when an undef value was passed as lvm::logical_volume name, mkfs was called with unwanted command line like

```
Error: Execution of 'mkfs.ext4 /dev/rootvg/' returned 1: mke2fs 1.42.9 (28-Dec-2013)
/dev/rootvg/ is not a block special device.
Proceed anyway? (y,n)
Error: /Stage[main]/Main/Lvm::Logical_volume[undef]/Filesystem[/dev/rootvg/]/ensure: change from absent to present failed: Execution of 'mkfs.ext4 /dev/rootvg/' returned 1: mke2fs 1.42.9 (28-Dec-2013)
/dev/rootvg/ is not a block special device.
Proceed anyway? (y,n)
```